getter functions from SC; duration until fundraising end date
buidlone/frontend pull request #106
Opened 2022-10-31 12:35 UTC by gabyteera

2022-11-01 07:20 UTC, BenasVolkovas requested changes

2022-11-01 07:20 UTC, BenasVolkovas commented on src/components/progressRoadmap/index.tsx
> +  let timeTillNextMilestone = useCountdown(
Project has more states that should be handled:
On state before fundraiser -> `2`, should show the time that is left until the fundraiser start.
On state fundraiser ongoing -> `4`, should show the time that is left until the fundraiser end.
On state fundraiser ended and no milestone ongoing -> `16`, should show the time that is left until the first milestone start date (`milestones[currentMilestone].startDate`)
On state milestone ongoing -> `32` or `64`, should show the time that is left until next milestone's start (`milestones[currentMilestone + 1].startDate`)

Also if the project failed or has successfully ended, this variable should not return any number. Else user might think that project is still ongoing.  
States when number shouldn't be returned: 1, 8, 128, 256, 512, 1024.

Don't forget to update text displayed for users (https://github.com/buidlone/frontend/blob/05c09bd09f2b65bebabad4b13367c5102e984df0/src/components/progressRoadmap/index.tsx#L196). **Next phase starts in:** should change respectively.

2022-11-03 07:47 UTC, GabijaBeres approved these changes

2022-11-03 08:12 UTC, gabyteera commented on src/components/progressRoadmap/index.tsx
> +  let timeTillNextMilestone = useCountdown(
Thank you. :) Changes will be implemented in the issue #109

2022-11-03 08:21 UTC, BenasVolkovas approved these changes

2022-11-03 08:22 UTC, merged