displaying milestones in timeline, progress comp.
buidlone/frontend pull request #99
Opened 2022-10-18 12:09 UTC by gabyteera

2022-10-18 13:04 UTC, GabijaBeres commented on src/components/progressRoadmap/styled.tsx
> +  unlocked?: boolean | null;
:(((((

2022-10-18 13:04 UTC, GabijaBeres commented on src/components/progressRoadmap/styled.tsx
> +  completed?: boolean | null;
please avoid null types :(

2022-10-18 13:09 UTC, GabijaBeres commented on src/hooks/useLoadValues.ts
> +  currentMilestone: null,
0

2022-10-18 13:10 UTC, GabijaBeres commented on src/interfaces/ILoadedValues.ts
> +  currentMilestone: number | null;
no null

2022-10-18 17:49 UTC, BenasVolkovas requested changes

2022-10-18 17:49 UTC, BenasVolkovas commented on src/utils/getMonthsBetween.ts
> +    return (inverse?-1:1)*(yearsDifference*12+monthsDifference+monthCorrection);
I don't think yearsDifference should be multiplied by 12. For example, date1 = 2022-11-01 and date2 = 2023-01-01. Current calculation will return that there is more than 12 months, which Is not correct.
My suggestion would be to subtract date timestamps first and then convert the value to date (months and days).

2022-10-18 17:49 UTC, BenasVolkovas commented on src/components/timelineBlock/index.tsx
> +    let projectPeriodInMonths = 0;
You can use `totalStreamingDuration()` function in investment pool to get the duration of project in seconds.

2022-10-18 17:49 UTC, BenasVolkovas commented on src/components/timelineGraph/index.tsx
> +                (projectState === 32 || projectState === 64) &&
I would advise to add a function something like `milestoneState(id)`, which will handle the checks, because in code same checks are repeated multiple time.

This function should handle active, ongoing and not started states.

2022-10-20 11:03 UTC, BenasVolkovas approved these changes
LGTM

2022-10-20 13:40 UTC, merged